[theme]
base = "light"
primaryColor = "#E4572E"
backgroundColor = "#F3EEE4"
secondaryBackgroundColor = "#FBF8F1"
textColor = "#14213D"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
